//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assemblies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assemblies()
        {
            this.AssemblyParts = new HashSet<AssemblyParts>();
        }
    
        public int AssemblyId { get; set; }
        public int UserId { get; set; }
        public string AssemblyName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyParts> AssemblyParts { get; set; }
    }
}
