//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyParts
    {
        public int ID { get; set; }
        public int AssemblyId { get; set; }
        public int PartId { get; set; }
    
        public virtual Assemblies Assemblies { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
