//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboDishes
    {
        public int ID { get; set; }
        public int ComdoID { get; set; }
        public int DishID { get; set; }
    
        public virtual Combos Combos { get; set; }
        public virtual Dishes Dishes { get; set; }
    }
}
