//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> DishID { get; set; }
        public Nullable<int> ComboID { get; set; }
        public int Quantity { get; set; }
        public decimal PriceAtOrder { get; set; }
    
        public virtual Combos Combos { get; set; }
        public virtual Dishes Dishes { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
