//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingForExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int ID { get; set; }
        public int ID_Master { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ID_Haircut { get; set; }
        public string Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public bool IsBooked { get; set; }
    
        public virtual Haircuts Haircuts { get; set; }
        public virtual Masters Masters { get; set; }
    }
}
