//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewRatings
    {
        public int ReviewRatingId { get; set; }
        public int ReviewId { get; set; }
        public int CriterionId { get; set; }
        public int Score { get; set; }
    
        public virtual RatingCriteria RatingCriteria { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}
